// env.ts
export const env = {
  NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL!,
  COOKIE_DOMAIN: process.env.COOKIE_DOMAIN!,
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL!,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN!,
  SESSION_TTL_SECONDS: process.env.SESSION_TTL_SECONDS!,
};
