// env.ts
export const env = {
  OPENAI_API_KEY: process.env.OPENAI_API_KEY!,
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL!,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN!,
  SESSION_TTL_SECONDS: process.env.SESSION_TTL_SECONDS!,
};
